name: real_estate_assessment
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.3
  blurrycontainer: ^2.1.0
  lottie: ^3.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/realEstates/
    - assets/images/others/
    - assets/jsons/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueBlack.otf
          weight: 900
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueHeavy.otf
          weight: 800
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueMedium.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueRoman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueLight.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueUltraLight.otf
          weight: 200
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueThin.otf
          weight: 100



# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: true
  package: resources
  groups:
     # IMAGES
    - path: assets/images/realEstates
      class_name: RealEstateImage
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]

    - path: assets/images/others
      class_name: AppImage
      types: [.png, .jpg, jpeg]

      # Icons
    - path: assets/icons
      class_name: RealEstateIcon
      types: [.png, jpg, .jpeg]

      # Animation
    - path: assets/jsons
      class_name: RealEstateAnimation
      types: [.json]